import type { Metadata } from "next";
import LoginNavBar from "@/Components/Nav/authNavbar";
import { SidebarProvider } from "@/ContextApi/sidebar-context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <LoginNavBar />
      {children}
    </SidebarProvider>
  );
}
